language: go

sudo: false

before_script:
  - git clone --depth 1 https://github.com/sstephenson/bats.git
  - export PATH=$PATH:bats/bin

go:
  - 1.8
  - tip

script:
  - make

matrix:
  allow_failures:
    - go: tip

before_deploy:
  - make build_releases

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "qEfvM6OMsOf11FLEzIwpChltWJ1p2HamLghpu7ceRaL6rfO3Sf69GfRs+6TkvL31C7fPZA1AVhiJsi82EK4AphZhLZAyomHrCK3QaZHMw5GUcuKYR/KGHunjX49FVmxi5nO70+9Jm/bnkl9ZDSkWn9rEYgrgk3eNfC8waqVj8Z5Wnna/SdfI1T059iH//7gi3WwR9hU7zQ/7oma8Mx14zbUJzMZgAqjudOY7nmLnZXT/nxRNOTQIlT+xl60VpLFPo9IpkF11tqo4VIafElSmy6dhx/3nNvs5vmN7F8Dc/8NJGG9xNB3uQIBcvpHUGTg8ramN6tl6uWXjK+j+Kakc6alWeaWuHS8pKzHMsCBisJ4FRR718iajT4V0G2npb1xHhsvW7HPTnntVbe2huDklaiNzCUPnKR8njURgjkfNkwByz3dYSAEeGf5SpDVcxidtsqmB4qb6EqqttIVohWeE85a9bixIp9N7bSQpisu3ABQZKVdY69XVBMia4PVGoryalExtLS/dUjfIh2jaAn/U5qVcUiI2lcM2xbUUllech7M4goynC3Ha4A3u9vn7ulOBo7w92G3+XKECp5f/zrxTvqeZjBzUzi3257Y9/sknetR3x+YPQ7STY1N9Jl2HmHKd/o9F7/t9Fgnww1OM5OBveiwy4XTj3WH4rselqjsPFhQ"
  file_glob: true
  file: release/seaweed-cli_*
  on:
    repo: mdb/seaweed-cli
    tags: true

notifications:
  email:
    on_success: never
    on_failure: always
